language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer clear-cache
  - composer install --no-interaction

script:
  - composer ci

notifications:
    email: false
